-- MindPC database schema
-- Run once to set up all tables.

-- Users who log in to the dashboard
CREATE TABLE IF NOT EXISTS users (
  id             SERIAL PRIMARY KEY,
  name           TEXT        NOT NULL,
  email          TEXT        NOT NULL UNIQUE,
  password_hash  TEXT        NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One row per physical machine a user installs the desktop app on
CREATE TABLE IF NOT EXISTS devices (
  id           SERIAL PRIMARY KEY,
  user_id      INT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_name  TEXT        NOT NULL,
  platform     TEXT        NOT NULL,  -- e.g. "win32"
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One row per tracked application session (start → end)
CREATE TABLE IF NOT EXISTS sessions (
  id                SERIAL PRIMARY KEY,
  user_id           INT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id         INT         NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  client_session_id TEXT        NOT NULL UNIQUE, -- UUID generated by the desktop app to allow idempotent upserts
  app_name          TEXT        NOT NULL,        -- human-readable name, e.g. "Google Chrome"
  app_identifier    TEXT        NOT NULL,        -- executable name, e.g. "chrome.exe"
  start_time        TIMESTAMPTZ NOT NULL,
  end_time          TIMESTAMPTZ,                 -- NULL while session is still open
  duration_seconds  INT,                         -- filled in when the session closes
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast queries for "show me all sessions for user X on date Y"
CREATE INDEX IF NOT EXISTS idx_sessions_user_start
  ON sessions(user_id, start_time);
